### ISSUE TITLE
[META] Initial feedback

### ISSUE THREAD

**Issue by orenyk** [YaleSTC/android_testing_training#1]
Bearing in mind that I can't really critique the Android-y aspects of this, this looks like a great training problem for the team! Here are some thoughts in no particular order:

1. FYI, the app name has "gallery" misspelled (it should have two `L`'s, not sure if it matters or is worth changing.
2. Best practices - I like the flexibility introduced by the updates, but to me (using a RoR analogue), it feels like you're going over styling best practice, not really backend / Android / Java best practice. This isn't a problem per se, but I'm curious if there are other things that you'd want to cover? Of course, if we don't this to take hours then adding things is probably not the best approach 😛.
3. Testing - is testing private methods encouraged? Everything I've read says that you should only test the public interfaces of your classes / objects and leave the private methods as implementation details that aren't explicitly tested. If you feel like they need to be tested then you're probably better off extracting them to a separate class. Especially given the added complexity of such tests in Java / Android (according to the README), I'm not convinced that this is even something we should be doing unless it's considered to be best practice in Android.
4. Testing (static) - the dummy example you presented doesn't convince me that static methods necessarily cause testing problems, rather that the code needs to be refactored 😛. In general, I've found that if your code doesn't lend itself to being tested easily, then that indicates that there's probably a better way to write it. If we turn things around, doing TDD (writing tests first) should ensure that you only write easily testable methods and don't end up in situations like that. I guess what I'm getting at is that I'm not clear on the conclusion I'm meant to be drawing from your discussion on static functions.

Otherwise this looks great, let me know what you think!

**Comment by stswidwinski** [comment]
1. Yeah, I noticed it but it was a tad late to change things... ill change it tmr and push changes ^^ 
2. I wanted to focus on front-end, since "best practices" in java as such are hard to convey in a single exercise. I'll focus on best practices in language and back end in code-reviews. Note that the app we are writing does not have much back-end at all either so I wanted to focus on the important parts (at least important to us right now)
3. Hell yeah! http://stackoverflow.com/questions/34571/how-to-test-a-class-that-has-private-methods-fields-or-inner-classes this is one of many such discussions. As a rule of thumb, private methods are usually helper-methods introduced either to modularize or to break up huge public functions. Thus, tests might not only be beneficial, but even make debugging of public interfaces easier! 

In general, there is nothing special about private functions in terms of testing -- they need it as well! :-) Let me know if you disagree! This applies to all languages out there and such tests should, in my mind, not be written only for libraries that are NOT our own (since private functions and their implementations might change without warning). Otherwise, all code within private functions must behave properly too and so must be tested 

4. Good point! I'll change the wording. What I'm trying to say there is that static methods that are relevant to the logic of execution are in general a bug, since they are hard to debug. The google article I linked explains this in painful detail ^^

**Comment by orenyk** [comment]
1. 👍
2. Makes sense to me, the principles (DRY, extensibility) are applicable wherever so the front-end seems as good a place as any to teach them.
3. I'm going to have to disagree here - if you're doing proper Object-Oriented Design then those private helper methods should likely be extracted into small single-purpose classes with their own public interfaces that can be easily unit-tested. Even though this method results in a substantially larger number of "objects" in our system, because they're all simpler (and easier to test!) then it makes reasoning about them and changing them easier down the road. Here's a [slide deck](https://speakerdeck.com/skmetz/magic-tricks-of-testing-railsconf) from Sandi Metz about testing and if you haven't read [POODR](http://www.poodr.com/) yet then I'd strongly recommend it - the examples are in Ruby but the principles are universal (and the testing stuff is covered at the end). We have a hard copy at 143 Elm but I can share a PDF with you as well - I think it will get the point across better than I can.
5. So basically the point is not "here are some annoying things you need to deal with to test static methods," but rather "here is why using static methods in this way is an anti-pattern / code smell and should be refactored"? That makes sense to me 😄.

**Comment by stswidwinski** [comment]
2. :+1: 
3. Interesting -- I'll take a look at the book when I'm back :-). I'm not sure whether I agree or disagree. In the general case of substantial (over)use of private methods, a new class with a good public interface makes sense. However, oftentimes the logic that you are proposing to extract to its own class is just not substantial enough and/or manipulates the inner fields of a class that should not be exposed. Defining a new class in this situation might just lead to confusion and a huge number of classes (some of which will likely by poorly named, because let's face it humans make mistakes).

Let me restructure that part in the tutorial for now -- I'll just state that sometimes one might want to test a private method (for instance maintaining legacy code that we have no time / don't want to refactor) and there is a way of doing it. In general, reflection is an amazing (and terrible) feature that people should be aware of ^^.
4. Yup, exactly ^^. That said, if one HAS to test such code, it is testable with more advanced injection that and the reason for that is how compilers are built (and "traditional" testing frameworks that cannot inject static methods)

**Comment by stswidwinski** [comment]
Okay:

1. Fixed (more work then I expected since rebasing had a billion conflicts haha). 
3. Reworded. 
4. Reworded

I have also made extensive changes to UI Tests as to eliminate race conditions that were present before. Now the test is sound, uses the "good" practice of good IdleResource class and is much longer. It also illustrates usage of reflection (by chance). Fun stuff. I think this should all work fine now.

**Comment by orenyk** [comment]
Nicely done, especially the test improvements 😄.

We should definitely have a longer conversation about general architecture / OOD practice (I think one of your arguments above is the [fear of adding classes](http://wiki.c2.com/?FearOfAddingClasses), which is something I still struggle with) - I'd like everything we do moving forward to be written in using best practices, so if that means throwing out legacy code and literally starting from scratch (with tests!) then that's what we'll do. All that said, if reflection is an important part of Java / Android development then we should definitely be teaching it.

I'm going to close this issue since I think we've covered everything I initially discussed. Nice job!
